### PR TITLE
Non nullable

### PR DESCRIPTION
**Pull request by mnordine**
@bp74 Sorry, but I didn't see a way for me to request a merge into a new branch, say `non-nullable`.

### CODE REVIEW

**Comment by bp74** [comment]
Very interessting! Did you do this by hand or does Dart already provide an tool to make those changes automatically?

**Comment by bp74** [comment]
I'm stupid! of course you did it by hand because i see all the commits. So what is the plan for Dart? I saw that they want to make the base libraries non-nullable first and then the third party libraries should build on that, right?

**Comment by bp74** [comment]
That's awesome!! Thank you very much for your great work.

My understanding is that the Dart Teams wants to make all the base libraries non-nullable first, and than the third party libraries should update to non-nullable too. Is this correct?

**Comment by mnordine** [comment]
@bp74 My pleasure, thanks for the great library to begin with!

> My understanding is that the Dart Teams wants to make all the base libraries non-nullable first

It depends on what you mean by base libraries I guess. But I think most, if not all, of the libraries authored by the Dart team have non-nullable versions.

As you can see, `xml` has a git branch, but I don't think they've published to `pub` yet.

Also, a little background on how I approached this. The first commit, https://github.com/bp74/StageXL/pull/338/commits/c6c747a4896f28431305c538e1960dc284a2acfb, was generated with `dart migrate`. It launches a web server, where you can visit a page on localhost, make some suggestions, and have it regenerate again. This tool is very nice to have, but it is just a tool, and only gets you so far. As you can see, I had to do quite a bit of work after that initial commit. I also found a bug in `dart migrate` that seems will be fixed as well.

**Comment by mnordine** [comment]
@bp74 I will also have MRs for some other StageXL libraries, such as BitmapFont, RichTextField.

**Comment by mnordine** [comment]
@bp74 So far, all the samples I've tried work without issue with this MR, but I'm going to continue testing, and will let you know if I run into any issues.

**Pull request merged**
