### PR TITLE
Analysis options

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by bp74** [comment]
Thanks a lot! Looks like there are many more options we have to activate in the analyzer in the future :)

**Comment by kevmoo** [comment]
Yup. But a good start.

**Comment by bp74** [comment]
The analyzer shows lots of hints regarding the return type of setters (should be void). Is this the recommended way to declare an setter or is this a wrong hint in the analyzer? Previously all samples showed setters without a "void" return type.

**Comment by kevmoo** [comment]
@bp74 I kinda like void for setters, personally.

We could/should start a discussion w/ Phil on the lint project

**Comment by bp74** [comment]
Yes i agree, it would be more consistent to add the void return type. If the linter thinks a void return type should be added, all the samples should be updated to.

**Comment by pq** [comment]
> Yes i agree, it would be more consistent to add the void return type. If the linter thinks a void return type should be added, all the samples should be updated to.

On the contrary!  That was a bug, setters should not require `void`.

Fixed here: https://github.com/dart-lang/linter/issues/192.

Feel free to open bugs on the [linter](https://github.com/dart-lang/linter/), if you see otherwise!

**Comment by nilsdoehring** [comment]
Applauding the fix, great work!

2016-04-18 18:49 GMT+02:00 Phil Quitslund <notifications@github.com>:

**Pull request merged**
