### PR TITLE
Add preventDefaultOnTouch property

### PR DESCRIPTION
**Pull request by xavierhainaux**
Hello Bernhard,
I would like to control whether StageXL calls “preventDefault” on the touch events.

Example where this can be useful:
On the iphone, there is the browser's bars that take a lot of space on the screen. The only way for the user to hide it, is to do a swipe gesture. But it requires that the canvas doesn’t call “preventDefault” or the canvas will swallow the event.
With this property, we can detect when the bar are visible (with window.innerHeight) and toggle the property for that time.

Without this property, to make it works, we add a div element above the canvas when the bar are visible but this has the disadvantage that it prevents every interactions with the canvas.

There is a similar use case on Chrome for android.

We can of course discuss another name for the property or even an alternative solution if you prefer.

Thank you.

### CODE REVIEW

**Comment by bp74** [comment]
Hi Xavier,

The next version of StageXL will contain more settings to control if an event should prevent it's default behavior or not. You can configure this option for Touch, Mouse, Wheel and Keyboard.

There is a global configuration like this:

     StageXL.stageOptions.preventDefaultOnTouch = true;
     StageXL.stageOptions.preventDefaultOnMouse = true;
     StageXL.stageOptions.preventDefaultOnWheel = false;
     StageXL.stageOptions.preventDefaultOnKeyboard = false;

But also a "preventDefault" method on each event if you need more control:

    void onTouch(TouchEvent te) {
      if (foo) te.preventDefault();
    }

I will release version 0.12 in the next few days. Hope this works for you!

**Comment by xavierhainaux** [comment]
That looks perfect Bernhard. I'll give it a try very soon.

Thank you very much.

**Comment by xavierhainaux** [comment]
Actually, I have one question.
In my original use case I wanted to change this options after the stage was initialized. 
(use case was: toggle the flag globally if the iphone browser's bar become visible).

I see in the implementation that you copy the option value in the constructor and so we cannot change the option later.

ie:
```dart
var options = new StageOptions();
var stage = new Stage(canvas, options: options);
options.preventDefaultOnTouch = false; // this won't works
```

Is it on purpose or can we allow it?

**Comment by bp74** [comment]
Okay is see. This is easy to change, there is no reason why we shouldn't change this after the stage was initialized.

**Comment by bp74** [comment]
Done! Now you can change the value at runtime. But it's not the "options" object you change, the properties are on the Stage. The options are only used in the constructor.

**Comment by xavierhainaux** [comment]
Great! Thank you.

**Pull request closed without merging**
