### PR TITLE
Sprite3D and TextFormat

### PR DESCRIPTION
**Pull request by nilsdoehring**
Hey Bernhard,
two changes that I'd find useful to find their way into StageXL:

1)
I've added a weight property to TextFormat and modified its _cssFontStyle getter in order to support font-weight. My use case is to be able to work with different font weights I obtain from Google Fonts.

2)
Make Sprite3D extend Sprite instead of DisplayObject3D. My use case is, that my framework requires functionality of Sprite, but also the option to use 3D features generically, so a 'real' Sprite3D is needed. I solved this by duplicating the code from DisplayObject3D – I couldn't find a more elegant way.

There's a third change (9c1fb6d) in the pull request by mistake. Please ignore – sorry for that.

Cheers, 
Nils

### CODE REVIEW

**Comment by bp74** [comment]
Thank! The changes to TextFormat are great and i will merge them right away. 
I have to take a look at the Sprite3D thing. Does all the Sprite feature still works as expected? Would it be possible to use a normal Sprite in your use case which has a Sprite3D as a child?

**Comment by nilsdoehring** [comment]
Isn't the only difference to the implementation as of today the graphics property and hitTest? 
I haven't seen any change in behavior in the three months since I made the changes to Stage3D in my fork.

Elaborating on the use case:
You might remember me working on a Material Design implementation. It uses Sprite's graphics property a lot. I have it implemented in a way to be 'render mode agnostic'. Now, if a Sprite3D incl. Graphics was available, I could simply change my central base class to use Sprite3D instead of Sprite, and would be able to apply 3D transformations as an icing on the cake when in WebGL mode.

**Comment by bp74** [comment]
I have merged the TextFormat changes but i did the Sprite3D implementation a little bit different. Instead of duplicating the code from DisplayObjectContainer3D i have copied the code from Sprite which is less code. Sprite3D implements the interface of Sprite now which should give you the same result. Could you try it for your use case and see if it works?

**Comment by bp74** [comment]
Nope, forget it - i am stupid ... doesn't work this way.

**Comment by bp74** [comment]
Okay, after some more thinking and fixes i think it works fine now. It would be great if you could give it a try :)

**Comment by nilsdoehring** [comment]
Thanks for addressing this so quickly - unfortunately, Sprite3D graphics are not drawn. I'll have a closer look tomorrow to see if I am able to circle this more closely.

**Comment by bp74** [comment]
Yes that's true, unfortunately. The reason is that there is no WebGL implementation for graphics yet :( This issue is on my todo list for some time but it is pretty complicated.

**Comment by nilsdoehring** [comment]
Sorry for being unprecise: I used applyCache.
The code below does **not** show a black rect in both render modes:
```
  var s = new Sprite3D();
  s.graphics.rect(0,0,200,50);
  s.graphics.fillColor(0xff000000);
  s.applyCache(0,0,200,50);
  stage.addChild(s);
```
- If Sprite is used instead, it **does** show a black rect in both render modes.
- If the version of Sprite3D I've added to this pull request is used instead, it **does** show a black rect  in both render modes.

**Comment by nilsdoehring** [comment]
Just found the reason: 
In Sprite3D, we need to add the render method from Sprite, too. 
```
  @override
  render(RenderState renderState) {
    if (_graphics != null) _graphics.render(renderState);
    super.render(renderState);
  }
```
Added it to the pull request.

**Comment by bp74** [comment]
Okay i see ... the thing could be even more complicated because the render method already has an override in the DisplayObjectCollection3D class. Those 3D classes are different to all other DisplayObjects because i don't want to have the complicated 3D calculations in the normal render path. The cache logic is outside of the specialized 3D render path ... anyway i will take a look at it!

**Comment by bp74** [comment]
I have committed a new version. The 3D render path has changed a little bit which makes 3D objects much more compatible with standard 2D objects. I will do some more optimizations over the next few days but the code should work now. As always, it would be great if you could give it a try.

**Comment by nilsdoehring** [comment]
Tested with Graphics rectangle, circle, rounded rect, line on Sprite3D, also in combination with filters, masks, and 3d manipulation. Works like a charm. 
Behaviour when falling back to CanvasRenderer also as expected: 3D and filters are not applied, without producing errors (or error messages).
Thanks so much!

**Comment by bp74** [comment]
Awesome! I think i will release version 0.12 later today - it's about time :)

**Comment by bp74** [comment]
Released with StageXL 0.12

**Pull request closed without merging**
