### PR TITLE
Completed gradient and pattern fill features

### PR DESCRIPTION
**Pull request by jwt-sgg**

### CODE REVIEW

**Comment by bp74** [comment]
Hi, thanks a lot! This is awesome!

I will review it over the weekend and probably merge it right away.

Thanks again for your work,
Bernhard

**Comment by jwt-sgg** [comment]
Hi, I updated the pull request to include a cache for shared CanvasPattern, CanvasGradient, and dynamically created RenderTexture objects. This allows equivalent gradient color stops to share a RenderTexture instead of a texture per fill, and similar sharing for RenderTextures that have to be cut out of an atlas.  The  CanvasPattern sharing is really a necessity for large applications since the Canvas Pattern actually copies the image being used, so each shape being filled would have a unique copy of the image if the pattern was not being shared.

**Comment by bp74** [comment]
Looks good, thanks! I already did a first review and everything looks very nice. I only found a few things where i might add/change a little bit of something, but i won't bother you with that and just add a few additional commits after the merge.

**Comment by jwt-sgg** [comment]
Sorry, I noticed I had left off a commit that made the pattern cache key work properly.  That has been included now.

**Pull request merged**
