### PR TITLE
Texture formats

### PR DESCRIPTION
**Pull request by mnordine**
Add support for various WebGL pixel formats and types.

Closes https://github.com/bp74/StageXL/issues/298

If this is acceptable, I also have a branch with compressed texture support that builds on this.

### CODE REVIEW

**Comment by xavierhainaux** [comment]
@mnordine I would love to see your branch with compressed texture if you have it online. Do you see some memory reduction?

**Comment by mnordine** [comment]
@xavierhainaux I will try to put it up soon, but yes, depending on the texture format, I've seen it go from 64MB to 10MB using PVR, for instance.

**Comment by xavierhainaux** [comment]
@mnordine thank you! It looks great. I want to try it soon in my project.

**Comment by mnordine** [comment]
@bp74 Just wondering if you got a chance to look at this? Is there maybe issues with it?

**Comment by bp74** [comment]
Sorry, i just hadn't enough time to work through the commits. I'm working on a very demanding project right now which should be finished in a few weeks. Then i will come back to your pull request.

**Pull request closed without merging**
