### PR TITLE
Webgl graphics

### PR DESCRIPTION
**Pull request by nilsdoehring**
Hi Bernhard,

while I don't expect you to accept this pull request directly, it might lead us to some rudimentary support for graphics on WebGL: rectangle and circle. Because you gotta start somewhere :-)

Basically, I copied the `Mask` rendering logic into the appropriate `_GraphicsCommand`. 

I then came up with a minimal invasive approach to address the obstacle, that WebGL triangles need color information *while* drawing. But that color info is stored away in `_GraphicsCommanfFillColor`, which is used in 2DCanvas *after* drawing. 

My approach introduces `GraphicsOptions`, which gets its attributes filled within the `Graphics.fill*` or `Graphics.stroke*` methods – for now, only `Graphics.fillColor`. 

Then, in `Graphics._renderWebGL`, the `GraphicsOptions` instance is supplied via `_GraphicsCommand*.drawWebGL`. 

In order to support multiple 'graphics objects' with different fillColors, a `_GraphicsCommandOptionsFlag` is inserted into the command chain as a flag whenever a new 'graphics object' is started (rect, circle, beginPath). Accordingly, a `List<GraphicsOptions>` is managed by `Graphics` and iterated through according to those flags in `_GraphicsCommand*.drawWebGL`.

I hope you can follow my logic(?). Please let me know what you think, and if possible, what needs to be done to get this into StageXL. I *really* could use support for WebGL rects and circles :-)

cheers,
Nils
P.S. Sorry for the mess, I have yet to find out how to include just my latest commit in a Pull Request.

### CODE REVIEW

**Comment by bp74** [comment]
Hi Nils,

Thanks for the pull request. It's really about time to do some work in this area. Your implementation made me think about one possibility: It's really hard to implement the full graphics API in WebGL and probably we will never get to this point. 

The thing what Pixi did is a much smaller graphics API but it is based on drawing triangles with Canvas2D and WebGL so you get a consistent output regardless if you use WebGL or Canvas2D. I would do the same in StageXL today but this is not an option because it would be a major breaking change. But there is another option - why not implement a new library (StageXL_Vector or whatever) which does this approach?

**Comment by nilsdoehring** [comment]
Hi Bernhard,

I get your point and gave this a second thought:
How about making Graphics an abstract class and have StageXL assign either CanvasGraphics or WebGLGraphics based on RenderMode (or dedicated StageOptions.enableWebGLGraphics) settings? This way, CanvasGraphics (and its _GraphicsCommands) could be stripped of anything WegGL and stay clean and stable; and with WebGLGraphics we could move forward step by step, of course without 'break changing' the underlying Graphics API.

**Comment by bp74** [comment]
I did some prototyping yesterday and the results are pretty good. I hope i can show you some of the stuff in a week or two - Milestone 1: Paths, Non-Zero Winding Rule and Solid Fills :)

**Comment by nilsdoehring** [comment]
I'm thrilled to have sparked your interest :-) Looking forward to the outcome, thanks!

**Comment by bp74** [comment]
If you are interested or curious, there is a branch of StageXL with some WebGL graphics!
https://github.com/bp74/StageXL/commits/webgl_graphics

You can use the following graphics mehtods:
moveTo, lineTo, rect, rectRound, circle, fillColor

Currently the bounds calculation and hitTest is disabled because of heavy refactoring :)
The other path methods (arc, actTo, quadraticCurveTo, bezierCurveTo) are coming next.

**Comment by bp74** [comment]
Just a quick update to keep you posted. The work is not done but things are looking good:
http://www.stagexl.org/temp/graphics_webgl/index.html

All path methods are implemented and you can fill those paths with a solid color.
The hitTest calculation as well as the bounds calculation is working fine.

Things that are not done yet:
Non-zero winding rule (i will do this with a stencil buffer, shouldn't be to hard)
Stroke commands (it's just a math exercise to calculate the triangles for the stroke)
Gradients (we will generate a texture with the gradient and map it to the triangles)
Patterns (should be similar to the Gradients).

I've merged the webgl_graphics branch to the master branch and will continue to work on the master branch. The architecture looks fine and i don't expect major reworks. I haven't done meaningful benchmarks, but the WebGL implementation seems to be faster then the Canvas2D implementation - which is very surprising.

I will close this pull request since those features should work fine with the new implementation. Please don't hesitate to open new issues or send feedback regarding this topic by mail.

**Pull request closed without merging**
