### PR TITLE
Add support for playing opus audio files

### PR DESCRIPTION
**Pull request by mnordine**
Opus info - http://caniuse.com/#search=opus

Unfortunately, there's currently a Chrome bug preventing this from working - https://bugs.chromium.org/p/chromium/issues/detail?id=409402

Works in FF

### CODE REVIEW

**Comment by bp74** [comment]
Thanks for this pull request. It's a good idea to support the opus codec. There is only one thing we should think about. In the audio_loader.dart file, the supportedTypes list defines also the priority of  the codecs. StageXL will load the file with the first supported audio codec in this list. Currently mp3 is in favor of ogg which is in favor of wav ... you get the idea.

So the question is if the opus codec should be moved to the start of the list, or at least before the ogg type. But if we move the opus codec to the front we will get a breaking change because the SoundLoadOptions sets the opus codec by default to true. If someone compiles his application with a new version of StageXL and the browser supports the opus format, then StageXL would try to load the opus file. Which will most likely fail because the application does not provide the opus files. The safest implementation would be to set the opus codec flag in the SoundLoadOptions by default to false.

What do you think?

**Comment by mnordine** [comment]
Due to the rarity of opus files, I agree it's prob best to default opus to false for now.

**Comment by bp74** [comment]
I think setting it to false is the right thing to do, if someone want's to use it he can easily opt in. Regarding the priority of the opus file, i think there was a misunderstanding. I was talking about the "_getSupportedTypes" method in "audio_loader.dart"

**Comment by mnordine** [comment]
Sorry, don't know what I was thinking there. It was early for me, :)

**Comment by bp74** [comment]
Great! Thank you very much, i will also add you to the authors file of StageXL

**Pull request merged**
