### PR TITLE
More dart2 Cleanup

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by nilsdoehring** [comment]
@bp74 please note that this PR will break compatibility with SDK 1.x.

**Comment by bp74** [comment]
@nilsdoehring yes i know, i won't publish it to pub

**Comment by kevmoo** [comment]
It'd be good to start moving folks towards Dart2, though. You could ditch pkg:browser and the webdev config, for example

**Comment by bp74** [comment]
Do you know when Dart 2 will be released? Everyone is talking about Flutter and nobody is talking about the web anymore, which is very unfortunate.

**Comment by kevmoo** [comment]
> Do you know when Dart 2 will be released? 
https://github.com/dart-lang/sdk/milestones

> Everyone is talking about Flutter and nobody is talking about the web anymore, which is very unfortunate.

We're working very hard on the web story. There is a lot of churn to the workflow, so we haven't wanted to get folks ramping up on all the new stuff until it's all working – we're VERY close.

**Pull request merged**
