### PR TITLE
Add null-check on format key

### PR DESCRIPTION
**Pull request by mnordine**
All previous tests were done with json files generated by
Texture Packer, which I thought always had the "format" key. However,
that appears to not be the case.

Note that in the absence of the "format" key, the render texture defaults to rgba 8888, as before.

### CODE REVIEW

**Comment by mnordine** [comment]
Fixes https://github.com/bp74/StageXL/issues/354

**Comment by kevmoo** [comment]
Will want to update pubspec and changelog for this fix!

**Comment by mnordine** [comment]
Whoever merges this will want to squash

**Comment by kevmoo** [comment]
Thanks so much! @bp74 ?

**Pull request merged**
